name: Docker
on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Piping Secrets
        run: |
          echo ${{ secrets.firebase_creds }} >> src/tests/firestore_creds.json
      - name: Building Image
        run: |
          docker build -f Dockerfile.dev -t mattgleich/vision:latest .
      - name: Testing Image
        run: |
          docker run -e CI=true mattgleich/vision
